### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by naloder** [iKirby/ShareHelper2#1]
当我试图添加移除参数时候，点击按钮，
发生了以下错误

android.view.InflateException: Binary XML file line #1 in me.ikirby.shareagent:layout/dialog_single_input: Binary XML file line #1 in me.ikirby.shareagent:layout/dialog_single_input: Error inflating class x
Caused by: android.view.InflateException: Binary XML file line #1 in me.ikirby.shareagent:layout/dialog_single_input: Error inflating class x
Caused by: java.lang.ClassNotFoundException: android.view.x
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at android.view.LayoutInflater.createView(LayoutInflater.java:817)
	at android.view.LayoutInflater.createView(LayoutInflater.java:778)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:915)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:68)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:932)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:952)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:661)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
	at e.b.c.i.onCreate(:4)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:421)
	at android.app.Dialog.show(Dialog.java:315)
	at f.b.a.a.a.n0(:3)
	at me.ikirby.shareagent.ParamsConfigActivity.onOptionsItemSelected(:2)
	at android.app.Activity.onMenuItemSelected(Activity.java:4385)
	at e.m.b.e.onMenuItemSelected(Unknown Source:0)
	at e.b.c.j.onMenuItemSelected(Unknown Source:0)
	at e.b.h.h.onMenuItemSelected(Unknown Source:2)
	at e.b.c.m.b(Unknown Source:22)
	at e.b.h.i.g.e(Unknown Source:4)
	at e.b.h.i.g.s(:1)
	at androidx.appcompat.widget.ActionMenuView.b(:1)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:7509)
	at android.view.View.performClickInternal(View.java:7486)
	at android.view.View.access$3600(View.java:841)
	at android.view.View$PerformClick.run(View.java:28709)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8070)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.ClassNotFoundException: android.view.x
	... 37 more

**Comment by iKirby** [comment]
Sorry for the inconvenience. A new version will be released on Play Store soon.
